print("hello world")
print("hello world again")
print("i like typing tis")
print("this is not fun")
print('yay! printing.')
print("i'd much rather you 'not'.")
print('i "said" do not touch this')